name: Update ONE-VIEW on new release
on:
  # Triggers the workflow on new release
  release:
    types: [published] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "echo-hello-world"
  echo-hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: create output folder
        run: |
          mkdir -p output-parser/${{ github.event.release.tag_name }}/{template-list,page,space,widget}
      - name: Repository Dispatch for one-view
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.repo_access }}
          repository: hotstar/one-view
          event-type: release
          client-payload: '{"version": "${{ github.event.release.tag_name }}"}'
