name: run script on new release
on:
  # Triggers the workflow on new release
  release:
    types: [published] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "echo-hello-world"
  echo-hello-world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python run.py
        env:
          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
